repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.0
    hooks:
      - id: clang-format

  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: run-clang-tidy -p=./build src
        language: system
        pass_filenames: false
